### PR TITLE
Making some major improvements

### PR DESCRIPTION
**Pull request by stjohnjohnson**
- Removing `/api/`
- Adding documentation to README
- Supporting hex colors like #FFF or #F0F0F0
- Adding `npm start` support

### CODE REVIEW

**Comment by d2lam** [comment]
👍

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by davglass** [comment]
Sorry, that was me testing the CLA hook on this repo :)

**Comment by stjohnjohnson** [comment]
No worries :)

**Pull request merged**
